### PR TITLE
Added catch for UnsupportedCharsetException when processing log encod…

### LINKED ISSUE #237: UnsupportedCharsetException: koi8r
Hello.
Looks like my issue is similar to #179
I receive the following errors:

```
Cleaning commits:         6% ( 12561/200493)Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.UnsupportedCharsetException: koi8r
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner.apply(ObjectIdCleaner.scala:75)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:113)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:112)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply$mcV$sp(RepoRewriter.scala:111)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:104)
	at com.madgag.git.bfg.Timing$.measureTask(timing.scala:40)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.clean$1(RepoRewriter.scala:104)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:145)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:60)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:35)
	at scala.Option.map(Option.scala:146)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:34)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:28)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:28)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.UnsupportedCharsetException: koi8r
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:61)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:87)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:85)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 28 more
Caused by: java.nio.charset.UnsupportedCharsetException: koi8r
	at java.base/java.nio.charset.Charset.forName(Charset.java:541)
	at org.eclipse.jgit.util.RawParseUtils.parseEncoding(RawParseUtils.java:791)
	at org.eclipse.jgit.revwalk.RevCommit.getEncoding(RevCommit.java:529)
	at com.madgag.git.bfg.model.CommitNode$.liftedTree1$1(Commit.scala:64)
	at com.madgag.git.bfg.model.CommitNode$.apply(Commit.scala:64)
	at com.madgag.git.bfg.model.Commit$.apply(Commit.scala:34)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:100)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:98)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:75)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 39 more

```

result of command 
```
git log --all --pretty=raw | grep "^encoding" | sort | uniq -c

   1 encoding cp1251
2716 encoding koi8r
```

### PR DESCRIPTION
**Pull request by javabrett**
…ing.  Fixed #237.

This is further to fix for #179, catching an additional exception.  Also updated test repo to contain an additional bad commit encoding header.

I guess the main question here is to go even broader with the catch - check for more likely IO/encoding exceptions, or just catch everything, since this is otherwise fatal.  For now I left it with adding the additional, single exception.

I assert that this patch is my own work, and to [simplify the licensing of the BFG Repo-Cleaner](https://github.com/rtyley/bfg-repo-cleaner/blob/master/CONTRIBUTING.md#pull-requests):

_(choose 1 of these 2 options)_

- [X] I assign the copyright on this contribution to Roberto Tyley
- [ ] I disclaim copyright and thus place this contribution in the public domain

### CODE REVIEW

**Comment by javabrett** [comment]
One thing to point out here is that this is working around a probably platform-specific issue. On Linux when I tested initially, IIRC encoding `koi8r` didn't cause a problem. Hence the test uses `impossibleencoding`.

So this change could result in success on two platforms with differing results due to BFG platform-available encodings. Not sure what to think of that. 

I guess that these occurrences should be debug logged or summary reported or both.

**Comment by rtyley** [comment]
> One thing to point out here is that this is working around a probably platform-specific issue. On Linux when I tested initially, IIRC encoding koi8r didn't cause a problem. Hence the test uses impossibleencoding.

Hi @javabrett , thanks for looking into this. When I look at the new version of `badEncoding.git.zip` it seems to be using `koi8r` rather than `impossibleencoding`? :

```
$ git cat-file -p a12735496c483af5a9adee8dcb62d38e64260446
tree 2b297e643c551e76cfa1f93810c50811382f9117
parent 0554b30af831719d1de53ee2ee8ff18d3f637953
author Brett Randall <javabrett@gmail.com> 1507504659 +1100
committer Brett Randall <javabrett@gmail.com> 1507504692 +1100
encoding koi8r

This commit message will have an unknown encoding header of: encoding koi8r.
```

I think that you're right, `impossibleencoding` would be better, because otherwise the new code path (catching the `UnsupportedCharsetException`) won't get exercised on running the test on machines that _do_ support `koi8r`.

**Comment by javabrett** [comment]
Yeah I have been sloppy with handling those zipped repos before.  This fix now cleans-up the `badEncoding.git.zip` which had become non-bare.  Should have the right new bad-encoding commit now, and I checked that it failed->passed test.

**Comment by StupidScience** [comment]
Just for info. I was tested it and everything worked well.

**Comment by rtyley** [comment]
Thanks for that success report @StupidScience , much appreciated! @javabrett, I see the new commit, looks good :+1:   :

```
$ git cat-file -p df78268ef6afaca63bd5d2eb370efe4d15fa23fd
tree 2b297e643c551e76cfa1f93810c50811382f9117
parent 0554b30af831719d1de53ee2ee8ff18d3f637953
author Brett Randall <javabrett@gmail.com> 1507763544 +1100
committer Brett Randall <javabrett@gmail.com> 1507763544 +1100
encoding impossibleencoding

This commit message will have an unknown encoding header of: encoding impossibleencoding.
```

**Pull request merged**
