### PR TITLE
Always use a static link to download the latest version from Maven Central

### PR DESCRIPTION
**Pull request by sschuberth**
[Review on Reviewable](https://reviewable.io/reviews/rtyley/bfg-repo-cleaner/124)

### CODE REVIEW

**Comment by rtyley** [comment]
Hi @sschuberth ,  thanks for your submission - this is touching on areas of design and UX, so unfortunately evaluation is going to be subject to gut instinct, personal taste, etc (unless we put prospective users in a UX lab :smile: ). It would help if you could give anecdotal evidence of one or more users who found the current behaviour confusing, or explain why it's more reliable/secure/ethical/etc to not dynamically-enhance the link.

Just to explain why I prefer the dynamically-enhanced link, it's basically because it replaces dependence on the (somewhat flakey) solr-backed search.maven.org service with a static, more reliable url, and it also behaves better with `wget` (the file saved has a better name):

```
$ wget https://repo1.maven.org/maven2/com/madgag/bfg/1.12.8/bfg-1.12.8.jar
Saving to: ‘bfg-1.12.8.jar’

$ wget "https://search.maven.org/remote_content?g=com.madgag&a=bfg&v=LATEST"
Saving to: ‘remote_content?g=com.madgag&a=bfg&v=LATEST’
```

**Comment by sschuberth** [comment]
Hi @rtyley! Downloading the latest version via `wget` (or `curl`, in my case) was exactly the use-case I had. To start with, it wasn't obvious to me how get a static link that points to the latest version at Maven Central. I was expecting I could just right click on the download button and select "Copy Link Location" in my browser (Firefox), but that didn't work because the dynamically created link with the version hard-coded is used. Also, there's a noticeable delay when loading the page until the button is rendered with the correct version number. I was hoping to speed this up a bit by removing some of the logic.

BTW, the ultimate goal for me was to create a [git alias for running bfg and downloading it](https://github.com/sschuberth/dev-scripts/blob/master/git/.gitconfig#L9), if required.

**Comment by sschuberth** [comment]
Also, the output naming issue can be easily solved by passing the `--content-disposition` option to `wget`.

**Comment by sschuberth** [comment]
@rtyley Have you made up your mind yet?

**Comment by rtyley** [comment]
Apologies for not getting back to you sooner - I think, of the two possible
options, linking to the specific versioned jar is better for the one-off
casual user, while using the always-latest link is better for educating
packagers/alias-creators who don't know the obscure maven search URL. As
the first set of people is probably larger, I think it's better to continue
with the specific versioned url.

@rtyley <https://github.com/rtyley> Have you made up your mind yet?

—
Reply to this email directly or view it on GitHub
<https://github.com/rtyley/bfg-repo-cleaner/pull/124#issuecomment-170940810>
.

**Comment by sschuberth** [comment]
@rtyley Ok. But how about at least cherry-picking [this commit](https://github.com/sschuberth/bfg-repo-cleaner/commit/870902d43265486b06a31f97bd95b1e0fd83004f)?

**Pull request closed without merging**
